var test_point = [
{"x_percentage": 71.386, "y_percentage": 76.240, "text": "Traumatología", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 13.294, "y_percentage": 26.834, "text": "Paranestesia", "building": "Pabellón Quirúrgico", "floor": "1", "comment": ""},
{"x_percentage": 13.294, "y_percentage": 26.834, "text": "Quirófanos", "building": "Pabellón Quirúrgico", "floor": "Bj", "comment": "Puede tratarse de otra planta según la operación"},
{"x_percentage": 32.114, "y_percentage": 40.017, "text": "Oncología", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 32.114, "y_percentage": 47.690, "text": "Colonoscopia", "building": "Pabellón A", "floor": "3", "comment": ""},                 
{"x_percentage": 32.114, "y_percentage": 47.690, "text": "Endoscopia", "building": "Pabellón A", "floor": "3", "comment": ""},
{"x_percentage": 32.114, "y_percentage": 47.690, "text": "Gastroscopia", "building": "Pabellón A", "floor": "3", "comment": ""},
{"x_percentage": 35.157, "y_percentage": 62.939, "text": "RayosX-Radiografías", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 31.702, "y_percentage": 65.109, "text": "Mamografía", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 31.844, "y_percentage": 67.481, "text": "Ecografía", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 34.411, "y_percentage": 70.907, "text": "Cardiología", "building": "Pabellón A", "floor": "2", "comment": "Se puede acceder por la planta baja,<br>en unas escaleras al fondo, pasado el TAC<br>Aquí tratan el tema de los marcapasos"},
{"x_percentage": 31.987, "y_percentage": 66.207, "text": "Hematología", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 31.987, "y_percentage": 66.207, "text": "Neurología - 2ª Opción", "building": "Pabellón A", "floor": "1", "comment": "Se viene aquí cuando se deriva del Pabellón B"},
{"x_percentage": 72.766, "y_percentage": 68.447, "text": "Neurología - 1ª Opción", "building": "Pabellón B", "floor": "1", "comment": "De aquí nos pueden derivar al Pabellón A - Primera planta"},
{"x_percentage": 30.989, "y_percentage": 68.008, "text": "Resonancia", "building": "Pabellón A", "floor": "Bj", "comment": ""},
{"x_percentage": 30.989, "y_percentage": 68.008, "text": "TAC", "building": "Pabellón A", "floor": "Bj", "comment": ""},
{"x_percentage": 31.131, "y_percentage": 69.238, "text": "Radioterapia", "building": "Pabellón A", "floor": "Bj", "comment": ""},
{"x_percentage": 88.308, "y_percentage": 17.410, "text": "Medicina Interna", "building": "Edificio Maternidad", "floor": "1", "comment": ""},
{"x_percentage": 72.624, "y_percentage": 71.214, "text": "Judiciales CNP", "building": "Pabellón B", "floor": "2", "comment": ""},
{"x_percentage": 72.624, "y_percentage": 71.214, "text": "Pruebas Funcionales - PFRM2", "building": "Pabellón B", "floor": "2", "comment": "Es la puerta donde está enfermería, al lado de CNP<br>De aquí nos pueden derivar a la planta 1ª"},
{"x_percentage": 31.429, "y_percentage": 43.362, "text": "Urgencias", "building": "Pabellón A", "floor": "Bj", "comment": ""},
{"x_percentage": 75.639, "y_percentage": 40.165, "text": "Infecciosos", "building": "Pabellón B", "floor": "1", "comment": "Acceso por el patio interior hacia B5"},
{"x_percentage": 72.256, "y_percentage": 39.123, "text": "Dermatología", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 75.639, "y_percentage": 38.706, "text": "Oftalmología", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 72.256, "y_percentage": 39.123, "text": "Reumatología", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 72.256, "y_percentage": 40.582, "text": "Endocrino", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 72.481, "y_percentage": 45.168, "text": "Urología", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 47.878, "text": "Cirugía Vascular", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 72.707, "y_percentage": 50.588, "text": "Cirugía Plástica", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 52.256, "text": "Alergología", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 76.090, "y_percentage": 50.380, "text": "Farmacía", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 80.376, "y_percentage": 58.093, "text": "Cirugía General y de mama", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 80.376, "y_percentage": 58.093, "text": "Cirugía General", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 80.376, "y_percentage": 58.093, "text": "Cirugía de mama", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 80.376, "y_percentage": 58.093, "text": "Gastroenterología", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 80.376, "y_percentage": 58.093, "text": "Digestivo", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 80.376, "y_percentage": 58.093, "text": "Hepatología", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 62.054, "text": "Nefrología", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 62.054, "text": "Electroencefalograma", "building": "Pabellón B", "floor": "3", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 64.139, "text": "Otorrino", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 64.139, "text": "Ortopantografía", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 76.316, "y_percentage": 64.347, "text": "Pruebas Otorrino", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 70.602, "text": "Neurocirugía", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 70.602, "text": "Neurofisiología", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 70.602, "text": "Raquis", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 72.932, "y_percentage": 70.602, "text": "Neurología", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 72.481, "y_percentage": 71.852, "text": "Nutrición y dietética", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 76.090, "y_percentage": 75.188, "text": "Odontoestomología", "building": "Pabellón B", "floor": "Bj", "comment": ""},
{"x_percentage": 75.865, "y_percentage": 66.849, "text": "Neumología", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 75.865, "y_percentage": 66.849, "text": "Gasometría", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 75.865, "y_percentage": 66.849, "text": "Espirometría", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 75.414, "y_percentage": 71.852, "text": "Cirugía Mayor Torácica", "building": "Pabellón B", "floor": "1", "comment": ""},
{"x_percentage": 88.496, "y_percentage": 17.650, "text": "Ginecología Urgencias", "building": "Edificio Maternidad", "floor": "4", "comment": ""},
{"x_percentage": 44.576, "y_percentage": 62.894, "text": "Analí­ticas", "building": "Patio Central", "floor": "Bj", "comment": "Se trata de un prefabricado temporal que se ubica cerca del acceso al Pabellón A desde el patio interior"},
{"x_percentage": 35.218, "y_percentage": 40.310, "text": "Unidad del dolor", "building": "Pabellón A", "floor": "2", "comment": "Acceso B3. Si no es correcto, comunicarlo, por favor."},
{"x_percentage": 48.546, "y_percentage": 0.267, "text": "Bar/ almuerzo", "building": "Fuera del recinto", "floor": "Bj", "comment": ""},
{"x_percentage": 75.804, "y_percentage": 69.746, "text": "Unidad del Íctus", "building": "Pabellón B", "floor": "3", "comment": "Está a la altura de judiciales CNP, en la siguiente planta"},
{"x_percentage": 75.395, "y_percentage": 70.577, "text": "Cirugí­a de Cólon", "building": "Pabellón B", "floor": "3", "comment": "Está a la altura de judiciales CNP, en la siguiente planta"},
{"x_percentage": 31.335, "y_percentage": 40.966, "text": "Diálisis", "building": "Pabellón A", "floor": "3", "comment": "Se accede por la entrada que hay junto a urgencias"},
];

var last_updates = ["30-10-2023 Añadido el punto Analíticas (Gracias por la colaboración)",
"30-10-2023 Añadido el punto Unidad del Dolor (Gracias por la colaboración)",
"30-10-2023 Incluído el apartado Últimas Actualizaciones",
"30-10-2023 Incluído el apartado Proponer Nuevo Punto",
"31-10-2023 Incluído el apartado Proponer modificación",
"31-10-2023 Añadido punto Bar/Almuerzo (Gracias por la colaboración)",
"31-10-2023 Se han especificado como obligatorios algunos campos mínimos para la introducción de puntos",
"31-10-2023 Se ha añadido un enlace a un pequeño videotutorial en la parte superior derecha de la página",
"03-11-2023 Se añade punto: Unidad del Íctus (Gracias por la colaboración)",
"03-11-2023 Se añade punto: Cirugía de Cólon (Gracias por la colaboración)",
"03-11-2023 Se añade punto: Diálisis (Gracias por la colaboración)",
]