var test_point = [
{"x_percentage": 71.386, "y_percentage": 76.240, "text": "Traumatología", "building": "Pabellón B", "floor": "Baja", "comment": ""},
{"x_percentage": 13.294, "y_percentage": 26.834, "text": "Paranestesia", "building": "Pabellón Quirúrgico", "floor": "1", "comment": ""},
{"x_percentage": 13.294, "y_percentage": 26.834, "text": "Quirófanos", "building": "Pabellón Quirúrgico", "floor": "Baja", "comment": "Puede tratarse de otra planta según la operación"},
{"x_percentage": 32.114, "y_percentage": 40.017, "text": "Oncología", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 32.114, "y_percentage": 47.690, "text": "Colonoscopia", "building": "Pabellón A", "floor": "3", "comment": ""},                 
{"x_percentage": 32.114, "y_percentage": 47.690, "text": "Endoscopia", "building": "Pabellón A", "floor": "3", "comment": ""},
{"x_percentage": 32.114, "y_percentage": 47.690, "text": "Gastroscopia", "building": "Pabellón A", "floor": "3", "comment": ""},
{"x_percentage": 35.157, "y_percentage": 62.939, "text": "RayosX-Radiografías", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 31.702, "y_percentage": 65.109, "text": "Mamografía", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 31.844, "y_percentage": 67.481, "text": "Ecografía", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 34.411, "y_percentage": 70.907, "text": "Cardiología", "building": "Pabellón A", "floor": "2", "comment": "Se puede acceder por la planta baja,<br>en unas escaleras al fondo, pasado el TAC<br>Aquí tratan el tema de los marcapasos"},
{"x_percentage": 31.987, "y_percentage": 66.207, "text": "Hematología", "building": "Pabellón A", "floor": "1", "comment": ""},
{"x_percentage": 31.987, "y_percentage": 66.207, "text": "Neurología - 2ª Opción", "building": "Pabellón A", "floor": "1", "comment": "Se viene aquí cuando se deriva del Pabellón B"},
{"x_percentage": 72.766, "y_percentage": 68.447, "text": "Neurología - 1ª Opción", "building": "Pabellón B", "floor": "1", "comment": "De aquí nos pueden derivar al Pabellón A - Primera planta"},
{"x_percentage": 30.989, "y_percentage": 68.008, "text": "Resonancia", "building": "Pabellón A", "floor": "Baja", "comment": ""},
{"x_percentage": 30.989, "y_percentage": 68.008, "text": "TAC", "building": "Pabellón A", "floor": "Baja", "comment": ""},
{"x_percentage": 31.131, "y_percentage": 69.238, "text": "Radioterapia", "building": "Pabellón A", "floor": "Baja", "comment": ""},
{"x_percentage": 88.308, "y_percentage": 17.410, "text": "Medicina Interna", "building": "Edificio Maternidad", "floor": "1", "comment": ""},
{"x_percentage": 72.624, "y_percentage": 71.214, "text": "Judiciales CNP", "building": "Pabellón B", "floor": "2", "comment": ""},
{"x_percentage": 72.624, "y_percentage": 71.214, "text": "Pruebas Funcionales", "building": "Pabellón B", "floor": "2", "comment": "Es la puerta donde está enfermería, al lado de CNP<br>De aquí nos pueden derivar a la planta 1ª"},
];